name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to use for deployment'
        required: true
        default: 'v1.0.0'
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Production
      run: |
        echo "Deploying to production..."
        # Add your actual deployment steps here
        echo "Application deployed!"

