name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      commit_id:
        description: 'Commit ID to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.commit_id }}

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Create a new tag
      id: create_tag
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        TAG="v$(date +'%Y%m%d%H%M%S')"
        echo "New tag will be $TAG"
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git tag $TAG
        git push https://${GITHUB_TOKEN}@github.com/ksaipavan13/simple-static-site.git $TAG
        echo "::set-output name=tag::$TAG"

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.create_tag.outputs.tag }}
        release_name: Release ${{ steps.create_tag.outputs.tag }}
        draft: false
        prerelease: false

    - name: Deploy to Production
      run: |
        echo "Deploying to production..."
        # Add your actual deployment steps here
        echo "Application deployed!"
