name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - update-version
  pull_request:
    branches:
      - main
      - update-version
  workflow_dispatch:
    inputs:
      commit_id:
        description: 'Commit ID to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.commit_id || github.sha }}

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Get version from package.json
      id: get_version
      run: |
        VERSION=$(jq -r '.version' package.json)
        echo "Version from package.json is $VERSION"
        echo "::set-output name=version::$VERSION"

    - name: Create and push tag
      id: create_tag
      uses: mathieudutour/github-tag-action@v6.0
      with:
        GITHUB_TOKEN: ${{ secrets.PAT }}
        tag_prefix: "v"
        create_annotated_tag: true
        tag: ${{ steps.get_version.outputs.version }}

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        tag_name: ${{ steps.create_tag.outputs.new_tag }}
        release_name: Release ${{ steps.create_tag.outputs.new_tag }}
        draft: false
        prerelease: false

    - name: Deploy to Production
      run: |
        echo "Deploying to production..."
        # Add your actual deployment steps here
        echo "Application deployed!"
